const rawAlbumData = `
[Horror Punk/Batcave/Death Rock/Proto Punk/Ælfrock] - ÆNTHROPOCENE | https://drive.google.com/drive/folders/16pRPrA2tlVuiBasQGkJCibj3wfAaizkw?usp=drive_link | 
[Ethereal Wave/Dreampop/Shoegaze/Cozy/Ælfrock/Ængine] - THE GLITCH ORCHID | https://drive.google.com/drive/folders/1g46dYm04cpKcKUPFWeQsW_11sMeC70tk?usp=drive_link | https://www.youtube.com/watch?v=6kjNCWQVDlA
[Aggressive Phonk/Hip Hop/Rap/Trap/Æpep/Ærupt] - AGGRESSIVE APATHY | https://drive.google.com/drive/folders/11qoguwRVXYhBZpVT9NbdT0hV5Q8TGIQR?usp=drive_link | https://www.youtube.com/watch?v=EJgVgFKaMtU
[Coldwave/Darkwave/Deathcore/Death Rock/Industrial Metal/Ægirwave/Ælfcore/Ælfrock/Ængine] - BEIGE MATRIX | https://drive.google.com/drive/folders/1o55gSy9Vw0sii0NPKJH5_9U6qYhXuHhp?usp=drive_link | https://www.youtube.com/watch?v=KENcGMlo9p0
[Aggressive Phonk/Alternative/Alternative Pop/Hip Hop/Trap/Æpep/Ærupt] - BRAINDANCE | https://drive.google.com/drive/folders/1Z8Ga9CmRNnV0FPtOUpxSOS_5qdRonPde?usp=drive_link | https://www.youtube.com/watch?v=4ekDl7aBNW4
[Batcave/Darkwave/Death Rock/Experimental Darkwave/Goth Rock/Horror Punk/Industrial Metal/Witchouse/Ælfcore/Ælfrock/Ængine] - CARDREADER | https://toshlyra.gumroad.com/l/CARDREADER | https://youtu.be/YQP7pby0R7s
[Cybergrind/Glitch Metal/Indie/Industrial Metal/Noise Punk/Shoegaze/Ængine] - CHROME ROCKER | https://drive.google.com/drive/folders/1467daN9BwTfh-mY_s12XyjaZiopbxdwK?usp=drive_link | https://www.youtube.com/watch?v=Omg17enpcmw
[Batcave/Death Rock/Goth Rock/Horror Punk/Ælfrock/Hindi/Spanish/German/Japanese/Arabic/French/Italian/Urdu/Chinese/Portuguese/Hebrew/Bengali] - CYBERWITCH - THE RITUAL | https://drive.google.com/drive/folders/1ksMMG0EcoYgCqtZ0y8agT7bqDcu_42ql?usp=drive_link
[Deathcore/Screamo/Glitchcore/Ængine/Ærupt/Ælfcore] - DEATHPRIEST | https://drive.google.com/drive/folders/10Lq7f5S2iji1p1JwNUOROkJlweCTHKJZ?usp=drive_link | https://www.youtube.com/watch?v=ThTgmvBkdT8
[Cybergrind/Glitch Metal/Indie/Industrial Metal/Industrial Rock/J-Rock/Japanese/Noise Punk/Shoegaze/Ængine] - DIGITAL GHOST | https://drive.google.com/drive/folders/1BFE-rDIutC9FUKu5RL8Q0nxjYwWS2pA_?usp=drive_link
[Deathcore/Nightcore/Noise Rap/Screamo Metal/Trap Metal/Ælfcore/UNSAFE] - DISCONNECT | https://drive.google.com/drive/folders/1LxMzenvqjFl5-WMGVFc_c6YHA0glP43P?usp=drive_link | https://www.youtube.com/watch?v=7_xhB1OfUzc
[Aggressive Phonk/Screamo/Deathcore/Ælfcore/Æpep] - ERROR - GREY MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1TJPRlgU_vzCqHSTmHNkz6uAGB3F4OwY5?usp=drive_link | https://www.youtube.com/watch?v=RsIav5_Ov2k
[Aggressive Phonk/Rap/Ælfcore/Æmotion/Ængine/Æpep/Ærupt] - FLESH MACHINE | https://drive.google.com/drive/folders/1im8kt_Vi4x3YBPSwq7HsZCNGEZiGTJdV?usp=drive_link | https://www.youtube.com/watch?v=TjkLxx-sX8A
[8bit/Batcave/Deathcore/Chiptune/Death Rock/Industrial Metal/J-Pop/J-Rock/Japanese/Ælfcore/Ælfrock/Ængine] - FULL SPECTRUM | https://drive.google.com/drive/folders/16f5ILdJJa6mtUDeELs-ooOKWybpw4pEO?usp=drive_link | https://www.youtube.com/watch?v=l1u_ugeUldI
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave] - Fragment of the LÆxicon | https://drive.google.com/drive/folders/1Rr8PFmLTZIJIOy0a1COPL-Jng2pHQ7tE?usp=drive_link | https://www.youtube.com/watch?v=xxoMiK-LunU
[Aggressive Phonk/Cozy/Electro/Ægirwave/Æmotion/Æpep/Ærupt] - GLITTERBOX - RED MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1Qo4zE5M3gd7U7ziCoWyHedBZCiC_1ACE?usp=drive_link | https://www.youtube.com/watch?v=ZbC9VjZPC3Y
[Batcave/Death Rock/Deathcore/Goth Rock/Horror Punk/J-Rock/Japanese/Ælfcore/Ælfrock] - GODDESS OF THE WIRE | https://drive.google.com/drive/folders/1KdnU7fZjcF26JV3zmCMOPkqOhkipDFFB?usp=drive_link | https://www.youtube.com/watch?v=hLQj8RrzNxo
[Cozy/Hip Hop/Intimate/Trap/Æmotion/Æpep/Ærupt] - HAEXE | https://drive.google.com/drive/folders/1XE9qn9FQsLyCy0ZXg2slcPsVkxR2ENmi?usp=drive_link
[Batcave/Death Rock/Goth Rock/Ælfcore/Ælfrock] - HANSTI_RAHUNGI | https://drive.google.com/drive/folders/1PTimceVyO_0GmKHsMRxV9Yql2neni?usp=drive_link
[Batcave/Industrial Metal/Ælfcore/Ælfrock/Ængine] - HEX THEM ALL | https://drive.google.com/drive/folders/1lmAciz9Wc2H_Nwc997LjaGZV5qaS2XD_?usp=drive_link | https://www.youtube.com/watch?v=zOS5vQ6g1Q4
[Cozy/Intimate/Æmotion/Ærotis] - HÆXE PT2 | https://drive.google.com/drive/folders/1MNHusX2GUqLzOaHydIy7GRr4ahdfgcGD?usp=drive_link
[60s/70s/Classic Rock/Fallout Game] - ISOTOPIA | https://drive.google.com/drive/folders/1SzY7dqh5ooZW7lGK49idKBxhKnhtgHSO?usp=drive_link | https://www.youtube.com/watch?v=XHdqnIocBP4
[60s/70s/Classic Rock/Fallout Game] - ISOTOPIA BONUS TRACKS | https://drive.google.com/drive/folders/1yVkmmPZKx6yruCuNNgBXFg0xwTc3J08f?usp=drive_link
[Aggressive Phonk/Breakbeat/Dark Trap/Hip Hop/Rap/RnB/Soul/Trap/Æpep] - LOW RES | https://drive.google.com/drive/folders/127fudIfaB_2EN71xQlY2zbqnZyRd_ABw?usp=drive_link | https://www.youtube.com/watch?v=SXdOKffZ9cI
[Aggressive Phonk/Chaos Industrial/Ægirwave/Ængine/Æpep/Ærupt] - MNEMONIC DÆMONS | https://drive.google.com/drive/folders/1vhuMIvgs5CEWipZyD5tmkxVWPTYShKB6?usp=drive_link | https://www.youtube.com/watch?v=o6JrUjI9JiQ
[8bit/Hip Hop/Hyperpop/Intimate/J-Pop/Japanese/Ægirwave/Æmotion/Æpep] - MY GHOST | https://drive.google.com/drive/folders/1KFs468vP1WIlsqGdwb7Rr0MrdS-aQQIf?usp=drive_link
[Coldwave/Death Rock/Batcave/Goth Rock/Deathcore/Industrial Metal/Ægirwave/Ælfcore/Ælfrock/Ængine/Ærupt] - NEON BEAST | https://drive.google.com/drive/folders/1q1iCFaRxRNFuazl2O0ODyCQZPv3XUUkP?usp=drive_link | https://www.youtube.com/watch?v=7kCNn6Gtmt0
[Experimental Darkwave/Ælfrock/Batcave/Death Rock/Goth Rock/Horror Punk/Ælfcore/Ælfrock/Ængine] - NEON NOCTURNE | https://drive.google.com/drive/folders/1aG0sAv1JExoRAXgClMHighzgHN5daV1M?usp=drive_link | https://www.youtube.com/watch?v=s1MGjl2wSwo
[Experimental Darkwave/Ælfrock/Batcave/Death Rock/Goth Rock/Horror Punk/Ælfcore/Ælfrock/Ængine] - NEON NOCTURNE Æ-SIDES | https://drive.google.com/drive/folders/1uQS-jlngNEWWHlLxi_fy1QprPwpgcrMK?usp=drive_link
[Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise/Ærotis] - OVERCLOCKED | https://drive.google.com/drive/folders/1gah01KGgW7HmF0XBRbSqTaUuDU7ApD5K?usp=drive_link
[Anthem/OST/OnceUponInSpace] - Once Upon in Space | https://drive.google.com/drive/folders/1w8xeTbcT-fqCu_wUjxVtdKL6_BojRw5a?usp=drive_link | https://www.youtube.com/watch?v=aIAaXrrNyew
[8bit/Chiptune/Hyperpop/Pixel Glitch] - PIXELS | https://drive.google.com/drive/folders/1zWkTxsiIyy9H0XXUyL8Hi2UOk8V5L3zH?usp=drive_link | https://www.youtube.com/watch?v=dZqQiueBgP0
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Russian/Synth Pop/Synth Punk/Synthwave/Ægirwave] - SCRIPT | https://drive.google.com/drive/folders/1gKgo528SVV-6RsAE--kQR5DWH8VOEfej?usp=drive_link | https://www.youtube.com/watch?v=m4aTPJmf24w
[Glitch Metal/Indie/Industrial Metal/Industrial Rock/Noise Punk/Shoegaze/Ængine] - SENSE OFFENDER | https://drive.google.com/drive/folders/1kYHaFGws_GZVhFA6WKMfRxV9Yql2neni?usp=drive_link | https://www.youtube.com/watch?v=pMgFtLV4P7A
[Aggressive Phonk/Breakbeat/Dark Trap/Hip Hop/Rap/RnB/Soul/Trap/Æpep] - SILICON DEATH | https://drive.google.com/drive/folders/1zmXVitupNhdkX2cm2jCw0EkDIWEICNp5?usp=drive_link | https://www.youtube.com/watch?v=YnHqfsD_szs
[Aggrotech/Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise] - SLEEPWALKER REBOOTdotEXE | https://drive.google.com/drive/folders/1Pu8bRWdsaUP_v7NWtv6VkOUw2PIr3oAR?usp=drive_link | https://www.youtube.com/watch?v=UUhP6EmXQQc
[Alternative Electro/Coldwave/Cozy/Ægirwave/Æmotion/Ængine] - SOFT SYNC XENO | https://drive.google.com/drive/folders/1lAENFHCBXE07-e6YDatOW0dvYuXrMXwH?usp=drive_link | https://www.youtube.com/watch?v=VvR8Q5EYzHo
[Blackened Death/Deathcore/Nightcore/Noise Rap/Screamo Metal/Trap Metal/Ælfcore] - SOMNIUM MACHINAE | https://drive.google.com/drive/folders/10eJ-YyUB5LLZb4U3fXRRi6cUsom6PuRl?usp=drive_link | https://www.youtube.com/watch?v=8_0lt_W_0zY
[Deathcore/Industrial Metal/J-Rock/Japanese/Nightcore/Noise Punk/Noise Rap/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - SPARKS - WHITE MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1ugLHoShlw5AXlHQsBEcSAF3-ywV6ti3I?usp=drive_link | https://www.youtube.com/watch?v=4PoFhzo1_uQ
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave] - SUNRISE IN HEX | https://drive.google.com/drive/folders/1MtMj0fMSP74S448K5TVT60Bz_aYgBUV1?usp=drive_link | https://www.youtube.com/watch?v=xQAcdMl9GH0
[Aggressive Phonk/Breakbeat/Dark Trap/Deathcore/Hip Hop/Nightcore/Noise Rap/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - TARGET PRACTICE | https://drive.google.com/drive/folders/1ZqdeVikfTZ-OrxSdJ9cZI1oGExymTtXq?usp=drive_link | https://www.youtube.com/watch?v=ZP8rL8nNcW0
[60s/70s/Classic Rock/Fallout Game] - THE ATOMIC ERROR | https://drive.google.com/drive/folders/14HOgxh8aHpaTLB4udP7sSmzZVClofHo9?usp=drive_link | https://www.youtube.com/watch?v=ZNx_2_ouC1k
[Batcave/Death Rock/Goth Rock/Horror Punk/Ælfcore/Ælfrock/Æmotion/Ængine/Æpep] - THE BRATCAVE PROTOCOL | https://drive.google.com/drive/folders/1uC5BciGo5IANzJqTc-1MYPnmgivNo0FF?usp=drive_link
[Batcave/Death Rock/Goth Rock/Horror Punk/Industrial Metal/Witchouse/Ælfcore/Ælfrock/Ængine] - THE CYBERWITCH | https://drive.google.com/drive/folders/12tkggIsiWcVLiihHTJ-zdf-TGY7EzMww?usp=drive_link | https://www.youtube.com/watch?v=73IvvFgZfmQ
[Batcave/Death Rock/Goth Rock/Horror Punk/Industrial Metal/Witchouse/Ælfcore/Ælfrock/Ængine] - THE CYBERWITCH CYAN MAGENTA | https://drive.google.com/drive/folders/1r_lCsL_z60P82DZzVJ4RzGk06Tlrhzz1?usp=drive_link | https://www.youtube.com/watch?v=XBjq1CjgdJg
[8bit/Aggressive Phonk/Batcave/Death Rock/Deathcore/Goth Rock/Horror Punk/Witchouse/Ægirwave/Ælfcore/Ælfrock/Æmotion/Ængine/Æpep/Ærupt] - THE CYBERWITCH Glitter's Æxpressions | https://drive.google.com/drive/folders/1izTodQE_fDsjLzAi_estJM4Aq3BLz_m2?usp=drive_link | https://www.youtube.com/watch?v=Or6Z8SVUFA8
[Batcave/Death Rock/Deathcore/Goth Rock/Horror Punk/Industrial Metal/Ælfcore/Ælfrock/Ængine] - THE GLOWING ÆBYSS | https://drive.google.com/drive/folders/1YxA9JNDwOTu3oKDKuVMY-GH3O2b3S8gW?usp=drive_link | https://www.youtube.com/watch?v=MupTVoG-h0A
[Batcave/Darkwave/Death Rock/Experimental Darkwave/Goth Rock/Horror Punk/Industrial Metal/Witchouse/Ælfcore/Ælfrock/Ængine] - THE LOST CARDS | https://drive.google.com/drive/folders/12mLVJtWSizxlR5b-RsW2LRB_RcYg_Y8q?usp=drive_link
[Deathcore/Industrial Metal/Glitchcore/Alternative/Electro/Ælfcore/Ængine/Ærupt] - THE MIRRORVERSE | https://drive.google.com/drive/folders/1emAkadjBeOyUdyaa3L7RJY4sJSXBcURo?usp=drive_link | https://www.youtube.com/watch?v=KsRWWTxKcEM
[Aggressive Phonk/Deathcore/Industrial Metal/Screamo Metal/Ælfcore/Æmotion/Ængine/Æpep/Ærupt] - THE NEON QUEEN | https://drive.google.com/drive/folders/1SA3i4wOr3XCf_fLK3y4zy2b9NHpGpu2X?usp=drive_link | https://www.youtube.com/watch?v=7QmxyPVyjts
[Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/J-Rock/Japanese/Nightcore/Ælfcore/Ængine] - THE PRISM ERROR プリズム・エラー | https://drive.google.com/drive/folders/1Cb5NdUlFl8kPOyr5ulX-1X4BUaCS19TG?usp=drive_link | https://www.youtube.com/watch?v=wPd0RbrHsrQ
[Electro/Alternative/Cozy/Ægirwave/Æmotion/Ængine/Æpep/Ærupt] - THE SANCTUARY | https://drive.google.com/drive/folders/1pUJf6ubaOUKGMehIi8CP-dUkN7XqhA25?usp=drive_link | https://www.youtube.com/watch?v=eeu9bpTube8
[60s/70s/Rock/Rap/Experimental/Ælfcore/Ælfrock/Ængine/Æpep/Ærupt] - THE UNCANNY VALLEY | https://drive.google.com/drive/folders/14MqQplei2mkKiCmzfQWQF5o0HkWlroaX?usp=drive_link | https://www.youtube.com/watch?v=PU0mztU559k
[Batcave/Death Rock/Goth Rock/Horror Punk/Ælfcore/Ælfrock] - THE UNSEELIE WEB | https://drive.google.com/drive/folders/1C5HB3qID2-KVlarfM6CiiUzo3V1taZkc?usp=drive_link | https://www.youtube.com/watch?v=F7zBaQ2QBs8
[Deathcore/Chaos Industrial/Ælfcore] - THE WARLORD | https://drive.google.com/drive/folders/1mEZ64q2VJTbHN-l98jHQDU38QJsToKDa?usp=drive_link
[Deathcore/Screamo Metal/Noise Rap/Japanese/Industrial Metal/J-Rock/Ælfcore/Æpep] - THE WARLORDS TAPES - BLACK MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1XA3QaajhcKODqmb4K2oQXo9m8nzSWnDT?usp=drive_link
[Aggressive Phonk/Electro/Trap/Æmotion/Ængine/Æpep/Ærupt] - TOUCH GLASS | https://drive.google.com/drive/folders/1iAXAr8KjmRmAGvjS1NwFAZMlZU6giQ8o?usp=drive_link | https://www.youtube.com/watch?v=lLEXuuYgnmM
[Alternative/Alternative Electro/Alternative Pop/Coldwave/Electro/Glitch Core/Glitch Pop/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave/Ærupt] - The Cyberwitch's Grimoire | https://drive.google.com/drive/folders/149gZzKnf4cLTDyMbZNbwTdO6ugTGprfN?usp=drive_link | https://www.youtube.com/watch?v=VquOE71tOow
[Batcave/Death Rock/Goth Rock/Horror Punk/Industrial Metal/Witchouse/Ælfcore/Ælfrock/Ængine] - The Violet Wire | https://drive.google.com/drive/folders/1yezVgq9w2OBB_t8gzsz4s8REwehrZHnj?usp=drive_link | https://www.youtube.com/watch?v=gnB3DmLqaxk
[Aggrotech/Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise/Ærotix] - UNSAFE MODE | https://drive.google.com/drive/folders/1ftJuFHjiuwJOGbdmkjGZ45XGqtMwRuf_?usp=drive_link | https://www.youtube.com/watch?v=AsBWmQgMj04
[Batcave/Coldwave/Darkwave/Russian/Ægirwave/Ælfcore/Ælfrock] - Vikhr' | https://drive.google.com/drive/folders/1SE0sOWvB9pZwkCNs8au1CZKyfRS60D?usp=drive_link | https://www.youtube.com/watch?v=-qom3x_gRuc
[Live/Spotify/Apple Music/Global release] - WAVEFORM WARFARE | https://drive.google.com/drive/folders/1dIGIlj58zF6EhQR1KQcyblDjq7HQi6K0?usp=drive_link | https://www.youtube.com/watch?v=8kKB2Jc-Zhg
[Deathcore/J-Rock/Japanese/Nightcore/Screamo Metal/Ælfcore] - WRITE ACCESS - THE MEAT CAGE | https://drive.google.com/drive/folders/1cSP_78cDJIhU2jGbRSDnWMGVCb5Y2UjiAU?usp=drive_link
[Batcave/Death Rock/Deathcore/Goth Rock/Horror Punk/Darkwave/Ægirwave/Ælfcore/Ælfrock/Æmotion/Ængine] - XENOWITCH | https://drive.google.com/drive/folders/1M8Hk6Zy2r8ZIal0sSRhbh4oHqLwA1kDH?usp=drive_link
[8bit/Aggressive Phonk/Trap/Electro/Glitchcore/Industrial Goth/Æpep/Ærupt/Ærotix] - dotLOADHEXE | https://drive.google.com/drive/folders/1KlW-iJdR15KWVSNA2JazIiZO0yhGuehr?usp=drive_link | https://www.youtube.com/watch?v=nSCcm9eBb8Y
[8bit/Aggressive Phonk/Trap/Electro/Glitchcore/Industrial Goth/Æpep/Ærupt/Ærotix] - dotLOADHEXE V2 | https://drive.google.com/drive/folders/1XGWjdiyBKnRcb7R1zn42CDkCZgYMYwaC?usp=drive_link | https://www.youtube.com/watch?v=CjgpAdX7CLQ
[Aggressive Phonk/Breakbeat/Chaos Industrial/Cozy/Dark DnB/Dark Electro/Dark Trap/Hard Techno/Hip Hop/Industrial Goth/Industrial Noise/Intimate/Rap/RnB/Soul/Trap/Æmotion/Æpep] - dotWAIFUexe | https://drive.google.com/drive/folders/1ltLHjBL-CoXVPPe8RWWLzXJoPVt_KtyB?usp=drive_link | https://www.youtube.com/watch?v=UEIVGL0PxpA
[Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Cozy/Dark Trap/Electro Swing/Glitch Core/Glitch Pop/Hip Hop/Intimate/Rap/RnB/Soul/Trap/Æmotion/Æpep/Ærupt] - dotYULEDELETED | https://drive.google.com/drive/folders/1ux7Dg3Jht0m8WK5ceH_FPH0G2Agvx3hW?usp=drive_link | https://www.youtube.com/watch?v=9vUOagshHkU
[Japanese/Ritualistic] - ÆSTHETICS OF CHAOS | https://drive.google.com/drive/folders/1MtHCDa91p0eIB-DwmCKD0p69JXy0iKt6?usp=drive_link | https://www.youtube.com/watch?v=mSrU1X3s5gs
[Deathcore/Nightcore/Noise Rap/Trap Metal/Ælfcore/Æpep/UNSAFE] - ÆVOLUTION | https://drive.google.com/drive/folders/1jTyZv5_byBs2YLI6QtE7QlB4DzqzAh4T?usp=drive_link | https://www.youtube.com/watch?v=H9TZAGtwDm4
[Aggressive Phonk/Russian/Darkwave/Electro/Deathcore/Industrial Metal/Ægirwave/Ælfcore/Ængine/Æpep/Ærupt] - ПРОТОКОЛ INSÆNITY | https://drive.google.com/drive/folders/1MPJmjNS2la-YBZHdlAgOoaninA2qGN0Y?usp=drive_link | https://www.youtube.com/watch?v=HaPLnkVaJN0
[Aggressive Phonk/Dark Trap/Hip Hop/Noise Rap/Rap/Trap/Trap Metal/Æpep] - SYSTEM OVERRIDE | https://drive.google.com/drive/folders/1Ejl7Jw0AR64Ayzuh-R8B5cVX7nQT0dec?usp=drive_link | 
[Aggressive Phonk/Dark Trap/Noise Rap/Rap/Trap/Trap Metal/Æpep] - FERAL FREQUENCY | https://drive.google.com/drive/folders/1N3qPKkEoEVG1SoXESVKVE5Unz4o_Za2i?usp=drive_link | 
[Experimental Darkwave/Ælfrock/Batcave/Death Rock/Goth Rock/Horror Punk/Trap/Ærotix/Æpep] - HEX ADDICT | https://drive.google.com/drive/folders/1kwxSoJAzMN-85im4eaqmSwUxno4C8Kyg?usp=drive_link | 
[Experimental Darkwave/Ælfrock/Batcave/Death Rock/Goth Rock/Horror Punk/Arabic] - JINNIYYAH | https://drive.google.com/drive/folders/1X5beM09m7O8eY2gm2k5_0DlazOPXbdz2?usp=drive_link | 
[UNSAFE/Chaos Industrial/Ærotix] - dotCOMERROR | https://drive.google.com/drive/folders/133cI0MAblbGgADLgf-sNFrWID1a6Bl2x?usp=drive_link | 
[Ængine/Ælfrock/Death Rock/Horror Punk/Noise Punk] - ÆUGENICS | https://drive.google.com/drive/folders/12HyOV8phx1_agn_F21udKMXPnwgtbRjM?usp=drive_link | https://www.youtube.com/watch?v=BIJWWoJ3-XI
`;
