// Paste your exact raw list between the backticks below!
const rawAlbumData = `
[Rap/Aggressive Phonk/Trap] - AGGRESSIVE APATHY | https://drive.google.com/drive/folders/11qoguwRVXYhBZpVT9NbdT0hV5Q8TGIQR?usp=drive_link
[Alternative Pop/Industrial Metal/Synth Punk] - BEIGE MATRIX | https://drive.google.com/drive/folders/1o55gSy9Vw0sii0NPKJH5_9U6qYhXuHhp?usp=drive_link
[Rap/Trap/Aggressive Phonk/Alternative Pop] - BRAINDANCE | https://drive.google.com/drive/folders/1Z8Ga9CmRNnV0FPtOUpxSOS_5qdRonPde?usp=drive_link
[Batcave/Death Rock/Goth Rock] - CARDREADER | https://toshlyra.gumroad.com/l/CARDREADER
[Industrial Metal/Alternative Rock/Alternative Pop] - CHROME ROCKER | https://drive.google.com/drive/folders/1467daN9BwTfh-mY_s12XyjaZiopbxdwK?usp=drive_link
[Batcave/Death Rock/Goth Rock/Multilanguage] - CYBERWITCH - THE RITUAL | https://drive.google.com/drive/folders/1ksMMG0EcoYgCqtZ0y8agT7bqDcu_42ql?usp=drive_link
[Rap/Trap/Alternative Electro] - DEATHPRIEST | https://drive.google.com/drive/folders/10Lq7f5S2iji1p1JwNUOROkJlweCTHKJZ?usp=drive_link
[J-Rock/Japanese] - DIGITAL GHOST | https://drive.google.com/drive/folders/1BFE-rDIutC9FUKu5RL8Q0nxjYwWS2pA_?usp=drive_link
[Deathcore/Ælfcore/Metal/Noise Trap] - DISCONNECT | https://drive.google.com/drive/folders/1LxMzenvqjFT5-WMGVFc_c6YHA0glP43P?usp=drive_link
[Ritual Electro/Alternative Electro] - dotLOADHEXE | https://drive.google.com/drive/folders/1KlW-iJdR15KWVSNA2JazIiZO0yhGuehr?usp=drive_link
[Ritual Electro/Alternative Electro/Ælfcore/Metal] - dotLOADHEXE V2 | https://drive.google.com/drive/folders/1XGWjdiyBKnRcb7R1zn42CDkCZgYMYwaC?usp=drive_link
[Rap/Dark Trap/Aggressive Phonk/Alternative Pop/Cozy] - dotWAIFUexe | https://drive.google.com/drive/folders/1ltLHjBL-CoXVPPe8RWWLzXJoPVt_KtyB?usp=drive_link
[Rap/Dark Trap/Aggressive Phonk/Alternative Pop] - dotYULEDELETED | https://drive.google.com/drive/folders/1ux7Dg3Jht0m8WK5ceH_FPH0G2Agvx3hW?usp=drive_link
[Ælfcore/Nightcore/Metal] - ERROR - GREY MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1TJPRlgU_vzCqHSTmHNkz6uAGB3F4OwY5?usp=drive_link
[Ælfcore/Nightcore/Screamo Metal/Alternative Pop/Alternative Electro] - FLESH MACHINE | https://drive.google.com/drive/folders/1im8kt_Wi4x3YBPSwq7HsZCNGEZiGTJdV?usp=drive_link
[Coldwave/Synthwave/Darkwave] - Fragment of the LÆxicon | https://drive.google.com/drive/folders/1Rr8PFmLTZIJIOy0a1COPL-Jng2pHQ7tE?usp=drive_link
[J-Rock/Hyperpop/Deathcore/Pixel Glitch/8Bit Pop/Russian/Japanese] - FULL SPECTRUM | https://drive.google.com/drive/folders/16f5ILdJJa6mtUDeELs-ooOKWybpw4pEO?usp=drive_link
[Alternative Electro/Japanese] - GLITTERBOX - RED MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1Qo4zE5M3gd7U7ziCoWyHedBZCiC_1ACE?usp=drive_link
[Ærotix/Cozy/Electro/Trap] - HAEXE | https://drive.google.com/drive/folders/1XE9qn9FQsLyCy0ZXg2slcPsVkxR2ENmi?usp=drive_link
[Alternative Rock/Death Rock/Batcave/Goth Rock] - HEX THEM ALL | https://drive.google.com/drive/folders/1lmAciz9Wc2H_Nwc997LjaGZV5qaS2XD_?usp=drive_link
[Ærotix/Cozy/Electro/Trap] - HÆXE PT2 | https://drive.google.com/drive/folders/1MNHusX2GUqLzOaHydIy7GRr4ahdfgcGD?usp=drive_link
[60s/70s/Rock/Country/Fallout Game] - ISOTOPIA | https://drive.google.com/drive/folders/1SzY7dqh5ooZW7lGK49idKBxhKnhtgHSO?usp=drive_link
[60s/70s/Rock/Country/Fallout Game] - ISOTOPIA BONUS TRACKS | https://drive.google.com/drive/folders/1yVkmmPZKx6yruCuNNgBXFg0xwTc3J08f?usp=drive_link
[Rap/Trap/Ælfcore/Cozy/Aggressive Phonk] - LOW RES | https://drive.google.com/drive/folders/127fudIfaB_2EN71xQlY2zbqnZyRd_ABw?usp=drive_link
[Industrial Noise/Alternative Electro/Glitch Core/Goth Electro] - MNEMONIC DÆMONS | https://drive.google.com/drive/folders/1vhuMIvgs5CEWipZyD5tmkxVWPTYShKB6?usp=drive_link
[J-Pop/Pixel Glitch/8Bit Pop/Russian/Alternative Electro/Japanese] - MY GHOST | https://drive.google.com/drive/folders/1KFs468vP1WIlsqGdwb7Rr0MrdS-aQQIf?usp=drive_link
[Alternative Rock/Coldwave/Alternative Pop/Screamo Metal] - NEON BEAST | https://drive.google.com/drive/folders/1q1iCFaRxRNFuazl2O0ODyCQZPv3XUUkP?usp=drive_link
[Noise Punk/Deathcore/Batcave/Death Rock/Goth Rock] - NEON NOCTURNE | https://drive.google.com/drive/folders/1aG0sAv1JExoRAXgClMHighzgHN5daV1M?usp=drive_link
[Noise Punk/Deathcore/Batcave/Death Rock/Goth Rock] - NEON NOCTURNE Æ-SIDES | https://drive.google.com/drive/folders/1uQS-jlngNEWWHlLxi_fy1QprPwpgcrMK?usp=drive_link
[Anthem/OST] - Once Upon in Space | https://drive.google.com/drive/folders/1w8xeTbcT-fqCu_wUjxVtdKL6_BojRw5a?usp=drive_link
[Ærotix/Hard Techno/Goth Electro] - OVERCLOCKED | https://drive.google.com/drive/folders/1gah01KGgW7HmF0XBRbSqTaUuDU7ApD5K?usp=drive_link
[Pixel Glitch/8Bit Pop] - PIXELS | https://drive.google.com/drive/folders/1zWkTxsiIyy9H0XXUyL8Hi2UOk8V5L3zH?usp=drive_link
[Coldwave/Russian/Post Punk] - SCRIPT | https://drive.google.com/drive/folders/1gKgo528SVV-6RsAE--kQR5DWH8VOEfej?usp=drive_link
[Noise Punk/Industrial Metal/Alternative Rock] - SENSE OFFENDER | https://drive.google.com/drive/folders/1kYHaFGws_GZVhFA6WKMfRxV9Yql2neni?usp=drive_link
[Ælfcore/Noise Rap/Unsafe] - SILICON DEATH | https://drive.google.com/drive/folders/1zmXVitupNhdkX2cm2jCw0EkDIWEICNp5?usp=drive_link
[Dark DnB/Breakbeat] - SLEEPWALKER  REBOOTdotEXE | https://drive.google.com/drive/folders/1Pu8bRWdsaUP_v7NWtv6VkOUw2PIr3oAR?usp=drive_link
[Cozy/Electro/Synth Pop] - SOFT SYNC XENO | https://drive.google.com/drive/folders/1lAENFHCBXE07-e6YDatOW0dvYuXrMXwH?usp=drive_link
[Ælfcore/Deathcore/] - SOMNIUM MACHINAE | https://drive.google.com/drive/folders/10eJ-YyUB5LLZb4U3fXRRi6cUsom6PuRl?usp=drive_link
[Screamo Metal/Nightcore/J-Rock] - SPARKS - WHITE MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1ugLHoShlw5AXlHQsBEcSAF3-ywV6ti3I?usp=drive_link
[80s/Synthwave/Synth Pop] - SUNRISE IN HEX | https://drive.google.com/drive/folders/1MtMj0fMSP74S448K5TVT60Bz_aYgBUV1?usp=drive_link
[Ælfcore/Noise Rap/Unsafe] - TARGET PRACTICE | https://drive.google.com/drive/folders/1ZqdeVikfTZ-OrxSdJ9cZI1oGExymTtXq?usp=drive_link
[60s/70s/Rock/Country/Fallout Game] - THE ATOMIC ERROR | https://drive.google.com/drive/folders/14HOgxh8aHpaTLB4udP7sSmzZVClofHo9?usp=drive_link
[Batcave/Death Rock/Goth Rock] - THE CYBERWITCH | https://drive.google.com/drive/folders/12tkggIsiWcVLiihHTJ-zdf-TGY7EzMww?usp=drive_link
[Batcave/Death Rock/Goth Rock] - THE CYBERWITCH CYAN MAGENTA | https://drive.google.com/drive/folders/1r_lCsL_z60P82DZzVJ4RzGk06Tlrhzz1?usp=drive_link
[Batcave/Death Rock/Goth Rock/Alternative Electro/Alternative Rock/Industrial Metal] - THE CYBERWITCH Glitter's Æxpressions | https://drive.google.com/drive/folders/1izTodQE_fDsjLzAi_estJM4Aq3BLz_m2?usp=drive_link
[Coldwave/Synthwave/Darkwave] - The Cyberwitch's Grimoire | https://drive.google.com/drive/folders/149gZzKnf4cLTDyMbZNbwTdO6ugTGprfN?usp=drive_link
[Batcave/Death Rock/Goth Rock/Alternative Rock/Brit Rock/Glitch Pop] - THE GLOWING ÆBYSS | https://drive.google.com/drive/folders/1YxA9JNDwOTu3oKDKuVMY-GH3O2b3S8gW?usp=drive_link
[Batcave/Death Rock/Goth Rock] - THE LOST CARDS | https://drive.google.com/drive/folders/12mLVJtWSizxlR5b-RsW2LRB_RcYg_Y8q?usp=drive_link
[Screamo Metal/Alternative Pop] - THE MIRRORVERSE | https://drive.google.com/drive/folders/1emAkadjBeOyUdyaa3L7RJY4sJSXBcURo?usp=drive_link
[Alternative Rock/Metal/Alternative Pop/Glitch Metal] - THE NEON QUEEN | https://drive.google.com/drive/folders/1SA3i4wOr3XCf_fLK3y4zy2b9NHpGpu2X?usp=drive_link
[J-Rock/J-Pop] - THE PRISM ERROR プリズム・エラー | https://drive.google.com/drive/folders/1Cb5NdUlFl8kPOyr5ulX-1X4BUaCS19TG?usp=drive_link
[Alternative Pop/Alternative Electro/Cozy] - THE SANCTUARY | https://drive.google.com/drive/folders/1pUJf6ubaOUKGMehIi8CP-dUkN7XqhA25?usp=drive_link
[Electro Swing/Phonk/Breakbeat/Aggressive Phonk/Alternative Electro] - THE UNCANNY VALLEY | https://drive.google.com/drive/folders/14MqQplei2mkKiCmzfQWQF5o0HkWlroaX?usp=drive_link
[Batcave/Death Rock/Goth Rock] - THE UNSEELIE WEB | https://drive.google.com/drive/folders/1C5HB3qID2-KVlarfM6CiiUzo3V1taZkc?usp=drive_link
[Ritual Electro/Witch House/Batcave/Death Rock/Goth Rock/Alternative] - The Violet Wire | https://drive.google.com/drive/folders/1yezVgq9w2OBB_t8gzsz4s8REwehrZHnj?usp=drive_link
[Screamo Metal/Deathcore/Goth Electro] - THE WARLORD | https://drive.google.com/drive/folders/1mEZ64q2VJTbHN-l98jHQDU38QJsToKDa?usp=drive_link
[J-Rock/Alternative Metal/Screamo Metal/Japanese] - THE WARLORDS TAPES - BLACK MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1XA3QaajhcKODqmb4K2oQXo9m8nzSWnDT?usp=drive_link
[Rap/Aggressive Phonk/Alternative Pop/Trap] - TOUCH GLASS | https://drive.google.com/drive/folders/1iAXAr8KjmRmAGvjS1NwFAZMlZU6giQ8o?usp=drive_link
[Industrial Noise/Industrial Goth] - UNSAFE MODE | https://drive.google.com/drive/folders/1ftJuFHjiuwJOGbdmkjGZ45XGqtMwRuf_?usp=drive_link
[Coldwave/Post Punk/New wave/Russian] - Vikhr' | https://drive.google.com/drive/folders/1SE0sOWvB9pBtZwkCNs8au1CZKyfRS60D?usp=drive_link
[Live] - WAVEFORM WARFARE | https://drive.google.com/drive/folders/1dIGIlj58zF6EhQR1KQcyblDjq7HQi6K0?usp=drive_link
[J-Rock/Alternative Metal/Japanese] - WRITE ACCESS - THE MEAT CAGE | https://drive.google.com/drive/folders/1cSP_78cDJIhU2jGbRSDnWCvb5Y2UjiAU?usp=drive_link
[Ritualistic/Japanese] - ÆSTHETICS OF CHAOS | https://drive.google.com/drive/folders/1MtHCDa91p0eIB-DwmCKD0p69JXy0iKt6?usp=drive_link
[Ælfcore/Noise Rap/Unsafe] - ÆVOLUTION | https://drive.google.com/drive/folders/1jTyZv5_byBs2YLI6QtE7QlB4DzqzAh4T?usp=drive_link
[Alternative Pop/Alternative Metal/Alternative Electro/Russian] - ПРОТОКОЛ INSÆNITY | https://drive.google.com/drive/folders/1MPJmjNS2la-YBZHdlAgOoaninA2qGN0Y?usp=drive_link
[J-Rock/Batcave/Death Rock/Goth Rock/Japanese] - GODDESS OF THE WIRE | https://drive.google.com/drive/folders/1KdnU7fZjcF26JV3zmCMOPkqOhkipDFFB?usp=drive_link
`;
