[Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Dark Trap/Electro Swing/Glitch Core/Glitch Pop/Hip Hop/Rap/RnB/Soul/Trap/Æpep/Ærupt] - AGGRESSIVE APATHY | https://drive.google.com/drive/folders/11qoguwRVXYhBZpVT9NbdT0hV5Q8TGIQR?usp=drive_link | https://www.youtube.com/watch?v=EJgVgFKaMtU
[Alternative Electro/Blackened Death/Coldwave/Cybergrind/Death Metal/Deathcore/Electro/Glitch Metal/Indie/Industrial Metal/Industrial Rock/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Post Punk/Screamo Metal/Shoegaze/Synth Pop/Synth Punk/Synthwave/Trap Metal/Ægirwave/Ælfcore/Ængine] - BEIGE MATRIX | https://drive.google.com/drive/folders/1o55gSy9Vw0sii0NPKJH5_9U6qYhXuHhp?usp=drive_link | https://www.youtube.com/watch?v=KENcGMlo9p0
[8bit/Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Chiptune/Dark Trap/Electro Swing/Glitch Core/Glitch Pop/Hip Hop/Hyperpop/Pixel Glitch/Rap/RnB/Soul/Trap/Æpep/Ærupt] - BRAINDANCE | https://drive.google.com/drive/folders/1Z8Ga9CmRNnV0FPtOUpxSOS_5qdRonPde?usp=drive_link | https://www.youtube.com/watch?v=4ekDl7aBNW4
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Live/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - CARDREADER | https://toshlyra.gumroad.com/l/CARDREADER | https://youtu.be/YQP7pby0R7s
[Cybergrind/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Noise Punk/Shoegaze/Ængine] - CHROME ROCKER | https://drive.google.com/drive/folders/1467daN9BwTfh-mY_s12XyjaZiopbxdwK?usp=drive_link | https://www.youtube.com/watch?v=Omg17enpcmw
[Blackened Death/Death Metal/Deathcore/Japanese/Nightcore/Noise Rap/Nu Metal/Russian/Screamo Metal/Trap Metal/Ælfcore] - CYBERWITCH - THE RITUAL | https://drive.google.com/drive/folders/1ksMMG0EcoYgCqtZ0y8agT7bqDcu_42ql?usp=drive_link
[Aggrotech/Alternative/Alternative Pop/Chaos Industrial/Cybergrind/Dark DnB/Dark Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hard Techno/Indie/Industrial Goth/Industrial Metal/Industrial Noise/Industrial Rock/Noise Punk/Shoegaze/Ængine/Ærupt] - DEATHPRIEST | https://drive.google.com/drive/folders/10Lq7f5S2iji1p1JwNUOROkJlweCTHKJZ?usp=drive_link | https://www.youtube.com/watch?v=ThTgmvBkdT8
[Cybergrind/Glitch Metal/Indie/Industrial Metal/Industrial Rock/J-Rock/Japanese/Noise Punk/Shoegaze/Ængine] - DIGITAL GHOST | https://drive.google.com/drive/folders/1BFE-rDIutC9FUKu5RL8Q0nxjYwWS2pA_?usp=drive_link
[Blackened Death/Death Metal/Deathcore/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - DISCONNECT | https://drive.google.com/drive/folders/1LxMzenvqjFl5-WMGVFc_c6YHA0glP43P?usp=drive_link | https://www.youtube.com/watch?v=7_xhB1OfUzc
[Aggressive Phonk/Blackened Death/Breakbeat/Dark Trap/Death Metal/Deathcore/Hip Hop/J-Rock/Japanese/Nightcore/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - ERROR - GREY MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1TJPRlgU_vzCqHSTmHNkz6uAGB3F4OwY5?usp=drive_link | https://www.youtube.com/watch?v=RsIav5_Ov2k
[Aggressive Phonk/Aggrotech/Alternative/Alternative Pop/Blackened Death/Breakbeat/Chaos Industrial/Cozy/Cybergrind/Dark DnB/Dark Electro/Dark Trap/Death Metal/Deathcore/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hard Techno/Hip Hop/Indie/Industrial Goth/Industrial Metal/Industrial Noise/Industrial Rock/Intimate/Nightcore/Noise Punk/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Shoegaze/Soul/Trap/Trap Metal/Ælfcore/Æmotion/Ængine/Æpep/Ærupt] - FLESH MACHINE | https://drive.google.com/drive/folders/1im8kt_Vi4x3YBPSwq7HsZCNGEZiGTJdV?usp=drive_link | https://www.youtube.com/watch?v=TjkLxx-sX8A
[8bit/Blackened Death/Chiptune/Cybergrind/Death Metal/Deathcore/Glitch Metal/Hyperpop/Indie/Industrial Metal/Industrial Rock/J-Pop/J-Rock/Japanese/Nightcore/Noise Punk/Noise Rap/Nu Metal/Pixel Glitch/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - FULL SPECTRUM | https://drive.google.com/drive/folders/16f5ILdJJa6mtUDeELs-ooOKWybpw4pEO?usp=drive_link | https://www.youtube.com/watch?v=l1u_ugeUldI
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave] - Fragment of the LÆxicon | https://drive.google.com/drive/folders/1Rr8PFmLTZIJIOy0a1COPL-Jng2pHQ7tE?usp=drive_link | https://www.youtube.com/watch?v=xxoMiK-LunU
[Aggressive Phonk/Aggrotech/Alternative/Alternative Electro/Alternative Pop/Breakbeat/Chaos Industrial/Coldwave/Cozy/Dark DnB/Dark Electro/Dark Trap/Electro/Electro Swing/Glitch Core/Glitch Pop/Hard Techno/Hip Hop/Industrial Goth/Industrial Noise/Intimate/J-Pop/Japanese/New Wave/Post Punk/Rap/RnB/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Ægirwave/Æmotion/Æpep/Ærupt] - GLITTERBOX - RED MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1Qo4zE5M3gd7U7ziCoWyHedBZCiC_1ACE?usp=drive_link | https://www.youtube.com/watch?v=ZbC9VjZPC3Y
[Blackened Death/Death Metal/Deathcore/J-Rock/Japanese/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - GODDESS OF THE WIRE | https://drive.google.com/drive/folders/1KdnU7fZjcF26JV3zmCMOPkqOhkipDFFB?usp=drive_link | https://www.youtube.com/watch?v=hLQj8RrzNxo
[Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Cozy/Dark Trap/Electro Swing/Glitch Core/Glitch Pop/Hip Hop/Intimate/Rap/RnB/Soul/Trap/Æmotion/Æpep/Ærupt] - HAEXE | https://drive.google.com/drive/folders/1XE9qn9FQsLyCy0ZXg2slcPsVkxR2ENmi?usp=drive_link
[Blackened Death/Death Metal/Deathcore/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - HANSTI RAHUNGI | https://drive.google.com/drive/folders/1PTimceVyO_0GmKHsMRxV9Yql2neni?usp=drive_link
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - HEX THEM ALL | https://drive.google.com/drive/folders/1lmAciz9Wc2H_Nwc997LjaGZV5qaS2XD_?usp=drive_link | https://www.youtube.com/watch?v=zOS5vQ6g1Q4
[Cozy/Intimate/Æmotion] - HÆXE PT2 | https://drive.google.com/drive/folders/1MNHusX2GUqLzOaHydIy7GRr4ahdfgcGD?usp=drive_link
[60s/70s/Classic Rock/Fallout Game] - ISOTOPIA | https://drive.google.com/drive/folders/1SzY7dqh5ooZW7lGK49idKBxhKnhtgHSO?usp=drive_link | https://www.youtube.com/watch?v=XHdqnIocBP4
[60s/70s/Classic Rock/Fallout Game] - ISOTOPIA BONUS TRACKS | https://drive.google.com/drive/folders/1yVkmmPZKx6yruCuNNgBXFg0xwTc3J08f?usp=drive_link
[Aggressive Phonk/Breakbeat/Dark Trap/Hip Hop/Rap/RnB/Soul/Trap/Æpep] - LOW RES | https://drive.google.com/drive/folders/127fudIfaB_2EN71xQlY2zbqnZyRd_ABw?usp=drive_link | https://www.youtube.com/watch?v=SXdOKffZ9cI
[Aggressive Phonk/Aggrotech/Alternative/Alternative Electro/Alternative Pop/Breakbeat/Chaos Industrial/Coldwave/Cybergrind/Dark DnB/Dark Electro/Dark Trap/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hard Techno/Hip Hop/Indie/Industrial Goth/Industrial Metal/Industrial Noise/Industrial Rock/New Wave/Noise Punk/Post Punk/Rap/RnB/Shoegaze/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Ægirwave/Ængine/Æpep/Ærupt] - MNEMONIC DÆMONS | https://drive.google.com/drive/folders/1vhuMIvgs5CEWipZyD5tmkxVWPTYShKB6?usp=drive_link | https://www.youtube.com/watch?v=o6JrUjI9JiQ
[8bit/Aggressive Phonk/Alternative Electro/Breakbeat/Chiptune/Coldwave/Cozy/Dark Trap/Electro/Hip Hop/Hyperpop/Intimate/J-Pop/Japanese/New Wave/Pixel Glitch/Post Punk/Rap/RnB/Russian/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Ægirwave/Æmotion/Æpep] - MY GHOST | https://drive.google.com/drive/folders/1KFs468vP1WIlsqGdwb7Rr0MrdS-aQQIf?usp=drive_link
[Alternative/Alternative Electro/Alternative Pop/Blackened Death/Coldwave/Cybergrind/Death Metal/Deathcore/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Indie/Industrial Metal/Industrial Rock/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Post Punk/Ritualistic/Screamo Metal/Shoegaze/Synth Pop/Synth Punk/Synthwave/Trap Metal/Ægirwave/Ælfcore/Ængine/Ærupt] - NEON BEAST | https://drive.google.com/drive/folders/1q1iCFaRxRNFuazl2O0ODyCQZPv3XUUkP?usp=drive_link | https://www.youtube.com/watch?v=7kCNn6Gtmt0
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Live/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - NEON NOCTURNE | https://drive.google.com/drive/folders/1aG0sAv1JExoRAXgClMHighzgHN5daV1M?usp=drive_link | https://www.youtube.com/watch?v=s1MGjl2wSwo
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - NEON NOCTURNE Æ-SIDES | https://drive.google.com/drive/folders/1uQS-jlngNEWWHlLxi_fy1QprPwpgcrMK?usp=drive_link
[Aggrotech/Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise] - OVERCLOCKED | https://drive.google.com/drive/folders/1gah01KGgW7HmF0XBRbSqTaUuDU7ApD5K?usp=drive_link
[Anthem/OST] - Once Upon in Space | https://drive.google.com/drive/folders/1w8xeTbcT-fqCu_wUjxVtdKL6_BojRw5a?usp=drive_link | https://www.youtube.com/watch?v=aIAaXrrNyew
[8bit/Chiptune/Hyperpop/Pixel Glitch] - PIXELS | https://drive.google.com/drive/folders/1zWkTxsiIyy9H0XXUyL8Hi2UOk8V5L3zH?usp=drive_link | https://www.youtube.com/watch?v=dZqQiueBgP0
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Russian/Synth Pop/Synth Punk/Synthwave/Ægirwave] - SCRIPT | https://drive.google.com/drive/folders/1gKgo528SVV-6RsAE--kQR5DWH8VOEfej?usp=drive_link | https://www.youtube.com/watch?v=m4aTPJmf24w
[Cybergrind/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Noise Punk/Shoegaze/Ængine] - SENSE OFFENDER | https://drive.google.com/drive/folders/1kYHaFGws_GZVhFA6WKMfRxV9Yql2neni?usp=drive_link | https://www.youtube.com/watch?v=pMgFtLV4P7A
[Aggressive Phonk/Blackened Death/Breakbeat/Dark Trap/Death Metal/Deathcore/Hip Hop/Nightcore/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - SILICON DEATH | https://drive.google.com/drive/folders/1zmXVitupNhdkX2cm2jCw0EkDIWEICNp5?usp=drive_link | https://www.youtube.com/watch?v=YnHqfsD_szs
[Aggrotech/Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise] - SLEEPWALKER REBOOTdotEXE | https://drive.google.com/drive/folders/1Pu8bRWdsaUP_v7NWtv6VkOUw2PIr3oAR?usp=drive_link | https://www.youtube.com/watch?v=UUhP6EmXQQc
[Alternative Electro/Coldwave/Cozy/Cybergrind/Electro/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Intimate/New Wave/Noise Punk/Post Punk/Shoegaze/Synth Pop/Synth Punk/Synthwave/Ægirwave/Æmotion/Ængine] - SOFT SYNC XENO | https://drive.google.com/drive/folders/1lAENFHCBXE07-e6YDatOW0dvYuXrMXwH?usp=drive_link | https://www.youtube.com/watch?v=VvR8Q5EYzHo
[Blackened Death/Death Metal/Deathcore/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - SOMNIUM MACHINAE | https://drive.google.com/drive/folders/10eJ-YyUB5LLZb4U3fXRRi6cUsom6PuRl?usp=drive_link | https://www.youtube.com/watch?v=8_0lt_W_0zY
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/J-Rock/Japanese/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - SPARKS - WHITE MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1ugLHoShlw5AXlHQsBEcSAF3-ywV6ti3I?usp=drive_link | https://www.youtube.com/watch?v=4PoFhzo1_uQ
[Alternative Electro/Coldwave/Electro/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave] - SUNRISE IN HEX | https://drive.google.com/drive/folders/1MtMj0fMSP74S448K5TVT60Bz_aYgBUV1?usp=drive_link | https://www.youtube.com/watch?v=xQAcdMl9GH0
[Aggressive Phonk/Blackened Death/Breakbeat/Dark Trap/Death Metal/Deathcore/Hip Hop/Nightcore/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - TARGET PRACTICE | https://drive.google.com/drive/folders/1ZqdeVikfTZ-OrxSdJ9cZI1oGExymTtXq?usp=drive_link | https://www.youtube.com/watch?v=ZP8rL8nNcW0
[60s/70s/Classic Rock/Fallout Game] - THE ATOMIC ERROR | https://drive.google.com/drive/folders/14HOgxh8aHpaTLB4udP7sSmzZVClofHo9?usp=drive_link | https://www.youtube.com/watch?v=ZNx_2_ouC1k
[8bit/Aggressive Phonk/Blackened Death/Breakbeat/Chiptune/Cozy/Cybergrind/Dark Trap/Death Metal/Deathcore/Glitch Metal/Hip Hop/Hyperpop/Indie/Industrial Metal/Industrial Rock/Intimate/Nightcore/Noise Punk/Noise Rap/Nu Metal/Pixel Glitch/Rap/RnB/Screamo Metal/Shoegaze/Soul/Trap/Trap Metal/Ælfcore/Æmotion/Ængine/Æpep] - THE BRATCAVE PROTOCOL | https://drive.google.com/drive/folders/1uC5BciGo5IANzJqTc-1MYPnmgivNo0FF?usp=drive_link
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - THE CYBERWITCH | https://drive.google.com/drive/folders/12tkggIsiWcVLiihHTJ-zdf-TGY7EzMww?usp=drive_link | https://www.youtube.com/watch?v=73IvvFgZfmQ
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - THE CYBERWITCH CYAN MAGENTA | https://drive.google.com/drive/folders/1r_lCsL_z60P82DZzVJ4RzGk06Tlrhzz1?usp=drive_link | https://www.youtube.com/watch?v=XBjq1CjgdJg
[8bit/Aggressive Phonk/Alternative/Alternative Electro/Alternative Pop/Blackened Death/Breakbeat/Chiptune/Coldwave/Cozy/Cybergrind/Dark Trap/Death Metal/Deathcore/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Hyperpop/Indie/Industrial Metal/Industrial Rock/Intimate/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Pixel Glitch/Post Punk/Rap/Ritualistic/RnB/Screamo Metal/Shoegaze/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Trap Metal/Ægirwave/Ælfcore/Æmotion/Ængine/Æpep/Ærupt] - THE CYBERWITCH Glitter's Æxpressions | https://drive.google.com/drive/folders/1izTodQE_fDsjLzAi_estJM4Aq3BLz_m2?usp=drive_link | https://www.youtube.com/watch?v=Or6Z8SVUFA8
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - THE GLOWING ÆBYSS | https://drive.google.com/drive/folders/1YxA9JNDwOTu3oKDKuVMY-GH3O2b3S8gW?usp=drive_link | https://www.youtube.com/watch?v=MupTVoG-h0A
[Alternative/Alternative Electro/Alternative Pop/Blackened Death/Coldwave/Cybergrind/Death Metal/Deathcore/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Indie/Industrial Metal/Industrial Rock/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Post Punk/Screamo Metal/Shoegaze/Synth Pop/Synth Punk/Synthwave/Trap Metal/Ægirwave/Ælfcore/Ængine/Ærupt] - THE LOST CARDS | https://drive.google.com/drive/folders/12mLVJtWSizxlR5b-RsW2LRB_RcYg_Y8q?usp=drive_link
[8bit/Alternative/Alternative Pop/Blackened Death/Chiptune/Cybergrind/Death Metal/Deathcore/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hyperpop/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Pixel Glitch/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine/Ærupt] - THE MIRRORVERSE | https://drive.google.com/drive/folders/1emAkadjBeOyUdyaa3L7RJY4sJSXBcURo?usp=drive_link | https://www.youtube.com/watch?v=KsRWWTxKcEM
[Aggressive Phonk/Alternative/Alternative Pop/Blackened Death/Breakbeat/Cozy/Cybergrind/Dark Trap/Death Metal/Deathcore/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Indie/Industrial Metal/Industrial Rock/Intimate/Nightcore/Noise Punk/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Shoegaze/Soul/Trap/Trap Metal/Ælfcore/Æmotion/Ængine/Æpep/Ærupt] - THE NEON QUEEN | https://drive.google.com/drive/folders/1SA3i4wOr3XCf_fLK3y4zy2b9NHpGpu2X?usp=drive_link | https://www.youtube.com/watch?v=7QmxyPVyjts
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/J-Rock/Japanese/Nightcore/Noise Punk/Noise Rap/Nu Metal/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - THE PRISM ERROR プリズム・エラー | https://drive.google.com/drive/folders/1Cb5NdUlFl8kPOyr5ulX-1X4BUaCS19TG?usp=drive_link | https://www.youtube.com/watch?v=wPd0RbrHsrQ
[Aggressive Phonk/Alternative/Alternative Electro/Alternative Pop/Breakbeat/Coldwave/Cozy/Cybergrind/Dark Trap/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Indie/Industrial Metal/Industrial Rock/Intimate/New Wave/Noise Punk/Post Punk/Rap/RnB/Shoegaze/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Ægirwave/Æmotion/Ængine/Æpep/Ærupt] - THE SANCTUARY | https://drive.google.com/drive/folders/1pUJf6ubaOUKGMehIi8CP-dUkN7XqhA25?usp=drive_link | https://www.youtube.com/watch?v=eeu9bpTube8
[60s/70s/8bit/Aggressive Phonk/Alternative/Alternative Pop/Blackened Death/Breakbeat/Chiptune/Classic Rock/Cybergrind/Dark Trap/Death Metal/Deathcore/Electro Swing/Fallout Game/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Hyperpop/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Pixel Glitch/Rap/RnB/Screamo Metal/Shoegaze/Soul/Trap/Trap Metal/Ælfcore/Ængine/Æpep/Ærupt] - THE UNCANNY VALLEY | https://drive.google.com/drive/folders/14MqQplei2mkKiCmzfQWQF5o0HkWlroaX?usp=drive_link | https://www.youtube.com/watch?v=PU0mztU559k
[Blackened Death/Death Metal/Deathcore/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - THE UNSEELIE WEB | https://drive.google.com/drive/folders/1C5HB3qID2-KVlarfM6CiiUzo3V1taZkc?usp=drive_link | https://www.youtube.com/watch?v=F7zBaQ2QBs8
[Aggrotech/Blackened Death/Chaos Industrial/Dark DnB/Dark Electro/Death Metal/Deathcore/Hard Techno/Industrial Goth/Industrial Noise/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - THE WARLORD | https://drive.google.com/drive/folders/1mEZ64q2VJTbHN-l98jHQDU38QJsToKDa?usp=drive_link
[Aggressive Phonk/Blackened Death/Breakbeat/Dark Trap/Death Metal/Deathcore/Hip Hop/J-Rock/Japanese/Nightcore/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - THE WARLORDS TAPES - BLACK MIRROR AEXPRESSIONS | https://drive.google.com/drive/folders/1XA3QaajhcKODqmb4K2oQXo9m8nzSWnDT?usp=drive_link
[Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Cozy/Cybergrind/Dark Trap/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Indie/Industrial Metal/Industrial Rock/Intimate/Noise Punk/Rap/RnB/Shoegaze/Soul/Trap/Æmotion/Ængine/Æpep/Ærupt] - TOUCH GLASS | https://drive.google.com/drive/folders/1iAXAr8KjmRmAGvjS1NwFAZMlZU6giQ8o?usp=drive_link | https://www.youtube.com/watch?v=lLEXuuYgnmM
[Alternative/Alternative Electro/Alternative Pop/Coldwave/Electro/Electro Swing/Glitch Core/Glitch Pop/New Wave/Post Punk/Synth Pop/Synth Punk/Synthwave/Ægirwave/Ærupt] - The Cyberwitch's Grimoire | https://drive.google.com/drive/folders/149gZzKnf4cLTDyMbZNbwTdO6ugTGprfN?usp=drive_link | https://www.youtube.com/watch?v=VquOE71tOow
[Blackened Death/Cybergrind/Death Metal/Deathcore/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Nightcore/Noise Punk/Noise Rap/Nu Metal/Ritualistic/Screamo Metal/Shoegaze/Trap Metal/Ælfcore/Ængine] - The Violet Wire | https://drive.google.com/drive/folders/1yezVgq9w2OBB_t8gzsz4s8REwehrZHnj?usp=drive_link | https://www.youtube.com/watch?v=gnB3DmLqaxk
[Aggrotech/Chaos Industrial/Dark DnB/Dark Electro/Hard Techno/Industrial Goth/Industrial Noise] - UNSAFE MODE | https://drive.google.com/drive/folders/1ftJuFHjiuwJOGbdmkjGZ45XGqtMwRuf_?usp=drive_link | https://www.youtube.com/watch?v=AsBWmQgMj04
[Aggrotech/Alternative Electro/Blackened Death/Chaos Industrial/Coldwave/Dark DnB/Dark Electro/Death Metal/Deathcore/Electro/Hard Techno/Industrial Goth/Industrial Noise/New Wave/Nightcore/Noise Rap/Nu Metal/Post Punk/Russian/Screamo Metal/Synth Pop/Synth Punk/Synthwave/Trap Metal/Ægirwave/Ælfcore] - Vikhr' | https://drive.google.com/drive/folders/1SE0sOWvB9pZwkCNs8au1CZKyfRS60D?usp=drive_link | https://www.youtube.com/watch?v=-qom3x_gRuc
[Live] - WAVEFORM WARFARE | https://drive.google.com/drive/folders/1dIGIlj58zF6EhQR1KQcyblDjq7HQi6K0?usp=drive_link | https://www.youtube.com/watch?v=8kKB2Jc-Zhg
[Blackened Death/Death Metal/Deathcore/J-Rock/Japanese/Nightcore/Noise Rap/Nu Metal/Screamo Metal/Trap Metal/Ælfcore] - WRITE ACCESS - THE MEAT CAGE | https://drive.google.com/drive/folders/1cSP_78cDJIhU2jGbRSDnWMGVCb5Y2UjiAU?usp=drive_link
[Alternative Electro/Blackened Death/Coldwave/Cozy/Cybergrind/Death Metal/Deathcore/Electro/Glitch Metal/Indie/Industrial Metal/Industrial Rock/Intimate/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Post Punk/Screamo Metal/Shoegaze/Synth Pop/Synth Punk/Synthwave/Trap Metal/Ægirwave/Ælfcore/Æmotion/Ængine] - XENOWITCH | https://drive.google.com/drive/folders/1M8Hk6Zy2r8ZIal0sSRhbh4oHqLwA1kDH?usp=drive_link
[8bit/Aggressive Phonk/Aggrotech/Alternative/Alternative Pop/Blackened Death/Breakbeat/Chaos Industrial/Chiptune/Dark DnB/Dark Electro/Dark Trap/Death Metal/Deathcore/Electro Swing/Glitch Core/Glitch Pop/Hard Techno/Hip Hop/Hyperpop/Industrial Goth/Industrial Noise/Nightcore/Noise Rap/Nu Metal/Pixel Glitch/Rap/Ritualistic/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep/Ærupt] - dotLOADHEXE | https://drive.google.com/drive/folders/1KlW-iJdR15KWVSNA2JazIiZO0yhGuehr?usp=drive_link | https://www.youtube.com/watch?v=nSCcm9eBb8Y
[Aggressive Phonk/Aggrotech/Alternative/Alternative Pop/Blackened Death/Breakbeat/Chaos Industrial/Dark DnB/Dark Electro/Dark Trap/Death Metal/Deathcore/Electro Swing/Glitch Core/Glitch Pop/Hard Techno/Hip Hop/Industrial Goth/Industrial Noise/Nightcore/Noise Rap/Nu Metal/Rap/Ritualistic/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep/Ærupt] - dotLOADHEXE V2 | https://drive.google.com/drive/folders/1XGWjdiyBKnRcb7R1zn42CDkCZgYMYwaC?usp=drive_link | https://www.youtube.com/watch?v=CjgpAdX7CLQ
[Aggressive Phonk/Aggrotech/Breakbeat/Chaos Industrial/Cozy/Dark DnB/Dark Electro/Dark Trap/Hard Techno/Hip Hop/Industrial Goth/Industrial Noise/Intimate/Rap/RnB/Soul/Trap/Æmotion/Æpep] - dotWAIFUexe | https://drive.google.com/drive/folders/1ltLHjBL-CoXVPPe8RWWLzXJoPVt_KtyB?usp=drive_link | https://www.youtube.com/watch?v=UEIVGL0PxpA
[Aggressive Phonk/Alternative/Alternative Pop/Breakbeat/Cozy/Dark Trap/Electro Swing/Glitch Core/Glitch Pop/Hip Hop/Intimate/Rap/RnB/Soul/Trap/Æmotion/Æpep/Ærupt] - dotYULEDELETED | https://drive.google.com/drive/folders/1ux7Dg3Jht0m8WK5ceH_FPH0G2Agvx3hW?usp=drive_link | https://www.youtube.com/watch?v=9vUOagshHkU
[Japanese/Ritualistic] - ÆSTHETICS OF CHAOS | https://drive.google.com/drive/folders/1MtHCDa91p0eIB-DwmCKD0p69JXy0iKt6?usp=drive_link | https://www.youtube.com/watch?v=mSrU1X3s5gs
[Aggressive Phonk/Blackened Death/Breakbeat/Dark Trap/Death Metal/Deathcore/Hip Hop/Nightcore/Noise Rap/Nu Metal/Rap/RnB/Screamo Metal/Soul/Trap/Trap Metal/Ælfcore/Æpep] - ÆVOLUTION | https://drive.google.com/drive/folders/1jTyZv5_byBs2YLI6QtE7QlB4DzqzAh4T?usp=drive_link | https://www.youtube.com/watch?v=H9TZAGtwDm4
[Aggressive Phonk/Alternative/Alternative Electro/Alternative Pop/Blackened Death/Breakbeat/Coldwave/Cybergrind/Dark Trap/Death Metal/Deathcore/Electro/Electro Swing/Glitch Core/Glitch Metal/Glitch Pop/Hip Hop/Indie/Industrial Metal/Industrial Rock/New Wave/Nightcore/Noise Punk/Noise Rap/Nu Metal/Post Punk/Rap/RnB/Russian/Screamo Metal/Shoegaze/Soul/Synth Pop/Synth Punk/Synthwave/Trap/Trap Metal/Ægirwave/Ælfcore/Ængine/Æpep/Ærupt] - ПРОТОКОЛ INSÆNITY | https://drive.google.com/drive/folders/1MPJmjNS2la-YBZHdlAgOoaninA2qGN0Y?usp=drive_link | https://www.youtube.com/watch?v=HaPLnkVaJN0
